"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BandlabIE = exports.AudiusIE = exports.YandexMusicIE = exports.Art19IE = exports.AcastIE = exports.SoundgasmIE = exports.MixcloudIE = exports.ApplePodcastsIE = exports.AudiomackIE = exports.OdnoklassnikiIE = exports.VKIE = exports.XiaoHongShuIE = exports.WeiboIE = exports.FC2IE = exports.YoukuIE = exports.IqiyiIE = exports.NaverIE = exports.AfreecaTVIE = exports.NiconicoIE = exports.PeertubeIE = exports.CoubIE = exports.NinegagIE = exports.NewgroundsIE = exports.BitchuteIE = exports.BlueskyIE = exports.PatreonIE = exports.KickIE = exports.RumbleIE = exports.BandcampIE = exports.BilibiliIE = exports.DailymotionIE = exports.SoundcloudIE = exports.RedditIE = exports.FacebookIE = exports.InstagramIE = exports.TwitterIE = exports.TiktokIE = exports.TwitchIE = exports.VimeoIE = exports.VoxMediaIE = exports.BitmovinIE = exports.BunnyCdnIE = exports.CloudflareStreamIE = exports.ThePlatformIE = exports.AnvatoIE = exports.KalturaIE = exports.WistiaIE = exports.JWPlatformIE = exports.BrightcoveIE = exports.YoutubeIE = void 0;
exports.ReverbNationIE = void 0;
exports.registerBuiltInExtractors = registerBuiltInExtractors;
const registry_1 = require("../core/registry");
const video_1 = require("./youtube/video");
Object.defineProperty(exports, "YoutubeIE", { enumerable: true, get: function () { return video_1.YoutubeIE; } });
// Batch 0 — embed / CDN platforms
const brightcove_1 = require("./brightcove");
Object.defineProperty(exports, "BrightcoveIE", { enumerable: true, get: function () { return brightcove_1.BrightcoveIE; } });
const jwplatform_1 = require("./jwplatform");
Object.defineProperty(exports, "JWPlatformIE", { enumerable: true, get: function () { return jwplatform_1.JWPlatformIE; } });
const wistia_1 = require("./wistia");
Object.defineProperty(exports, "WistiaIE", { enumerable: true, get: function () { return wistia_1.WistiaIE; } });
const kaltura_1 = require("./kaltura");
Object.defineProperty(exports, "KalturaIE", { enumerable: true, get: function () { return kaltura_1.KalturaIE; } });
const anvato_1 = require("./anvato");
Object.defineProperty(exports, "AnvatoIE", { enumerable: true, get: function () { return anvato_1.AnvatoIE; } });
const theplatform_1 = require("./theplatform");
Object.defineProperty(exports, "ThePlatformIE", { enumerable: true, get: function () { return theplatform_1.ThePlatformIE; } });
const cloudflarestream_1 = require("./cloudflarestream");
Object.defineProperty(exports, "CloudflareStreamIE", { enumerable: true, get: function () { return cloudflarestream_1.CloudflareStreamIE; } });
const bunnycdn_1 = require("./bunnycdn");
Object.defineProperty(exports, "BunnyCdnIE", { enumerable: true, get: function () { return bunnycdn_1.BunnyCdnIE; } });
const bitmovin_1 = require("./bitmovin");
Object.defineProperty(exports, "BitmovinIE", { enumerable: true, get: function () { return bitmovin_1.BitmovinIE; } });
const voxmedia_1 = require("./voxmedia");
Object.defineProperty(exports, "VoxMediaIE", { enumerable: true, get: function () { return voxmedia_1.VoxMediaIE; } });
// Batch 1 — global platforms
const vimeo_1 = require("./vimeo");
Object.defineProperty(exports, "VimeoIE", { enumerable: true, get: function () { return vimeo_1.VimeoIE; } });
const twitch_1 = require("./twitch");
Object.defineProperty(exports, "TwitchIE", { enumerable: true, get: function () { return twitch_1.TwitchIE; } });
const tiktok_1 = require("./tiktok");
Object.defineProperty(exports, "TiktokIE", { enumerable: true, get: function () { return tiktok_1.TiktokIE; } });
const twitter_1 = require("./twitter");
Object.defineProperty(exports, "TwitterIE", { enumerable: true, get: function () { return twitter_1.TwitterIE; } });
const instagram_1 = require("./instagram");
Object.defineProperty(exports, "InstagramIE", { enumerable: true, get: function () { return instagram_1.InstagramIE; } });
const facebook_1 = require("./facebook");
Object.defineProperty(exports, "FacebookIE", { enumerable: true, get: function () { return facebook_1.FacebookIE; } });
const reddit_1 = require("./reddit");
Object.defineProperty(exports, "RedditIE", { enumerable: true, get: function () { return reddit_1.RedditIE; } });
const soundcloud_1 = require("./soundcloud");
Object.defineProperty(exports, "SoundcloudIE", { enumerable: true, get: function () { return soundcloud_1.SoundcloudIE; } });
const dailymotion_1 = require("./dailymotion");
Object.defineProperty(exports, "DailymotionIE", { enumerable: true, get: function () { return dailymotion_1.DailymotionIE; } });
const bilibili_1 = require("./bilibili");
Object.defineProperty(exports, "BilibiliIE", { enumerable: true, get: function () { return bilibili_1.BilibiliIE; } });
// Batch 2 — VLC-oriented sites
const bandcamp_1 = require("./bandcamp");
Object.defineProperty(exports, "BandcampIE", { enumerable: true, get: function () { return bandcamp_1.BandcampIE; } });
const rumble_1 = require("./rumble");
Object.defineProperty(exports, "RumbleIE", { enumerable: true, get: function () { return rumble_1.RumbleIE; } });
const kick_1 = require("./kick");
Object.defineProperty(exports, "KickIE", { enumerable: true, get: function () { return kick_1.KickIE; } });
const patreon_1 = require("./patreon");
Object.defineProperty(exports, "PatreonIE", { enumerable: true, get: function () { return patreon_1.PatreonIE; } });
const bluesky_1 = require("./bluesky");
Object.defineProperty(exports, "BlueskyIE", { enumerable: true, get: function () { return bluesky_1.BlueskyIE; } });
const bitchute_1 = require("./bitchute");
Object.defineProperty(exports, "BitchuteIE", { enumerable: true, get: function () { return bitchute_1.BitchuteIE; } });
const newgrounds_1 = require("./newgrounds");
Object.defineProperty(exports, "NewgroundsIE", { enumerable: true, get: function () { return newgrounds_1.NewgroundsIE; } });
const ninegag_1 = require("./ninegag");
Object.defineProperty(exports, "NinegagIE", { enumerable: true, get: function () { return ninegag_1.NinegagIE; } });
const coub_1 = require("./coub");
Object.defineProperty(exports, "CoubIE", { enumerable: true, get: function () { return coub_1.CoubIE; } });
const peertube_1 = require("./peertube");
Object.defineProperty(exports, "PeertubeIE", { enumerable: true, get: function () { return peertube_1.PeertubeIE; } });
// Batch 3 — regional APIs
const niconico_1 = require("./niconico");
Object.defineProperty(exports, "NiconicoIE", { enumerable: true, get: function () { return niconico_1.NiconicoIE; } });
const afreecatv_1 = require("./afreecatv");
Object.defineProperty(exports, "AfreecaTVIE", { enumerable: true, get: function () { return afreecatv_1.AfreecaTVIE; } });
const naver_1 = require("./naver");
Object.defineProperty(exports, "NaverIE", { enumerable: true, get: function () { return naver_1.NaverIE; } });
const iqiyi_1 = require("./iqiyi");
Object.defineProperty(exports, "IqiyiIE", { enumerable: true, get: function () { return iqiyi_1.IqiyiIE; } });
const youku_1 = require("./youku");
Object.defineProperty(exports, "YoukuIE", { enumerable: true, get: function () { return youku_1.YoukuIE; } });
const fc2_1 = require("./fc2");
Object.defineProperty(exports, "FC2IE", { enumerable: true, get: function () { return fc2_1.FC2IE; } });
const weibo_1 = require("./weibo");
Object.defineProperty(exports, "WeiboIE", { enumerable: true, get: function () { return weibo_1.WeiboIE; } });
const xiaohongshu_1 = require("./xiaohongshu");
Object.defineProperty(exports, "XiaoHongShuIE", { enumerable: true, get: function () { return xiaohongshu_1.XiaoHongShuIE; } });
const vk_1 = require("./vk");
Object.defineProperty(exports, "VKIE", { enumerable: true, get: function () { return vk_1.VKIE; } });
const odnoklassniki_1 = require("./odnoklassniki");
Object.defineProperty(exports, "OdnoklassnikiIE", { enumerable: true, get: function () { return odnoklassniki_1.OdnoklassnikiIE; } });
// Batch 4 — audio / podcasts
const audiomack_1 = require("./audiomack");
Object.defineProperty(exports, "AudiomackIE", { enumerable: true, get: function () { return audiomack_1.AudiomackIE; } });
const applepodcasts_1 = require("./applepodcasts");
Object.defineProperty(exports, "ApplePodcastsIE", { enumerable: true, get: function () { return applepodcasts_1.ApplePodcastsIE; } });
const mixcloud_1 = require("./mixcloud");
Object.defineProperty(exports, "MixcloudIE", { enumerable: true, get: function () { return mixcloud_1.MixcloudIE; } });
const soundgasm_1 = require("./soundgasm");
Object.defineProperty(exports, "SoundgasmIE", { enumerable: true, get: function () { return soundgasm_1.SoundgasmIE; } });
const acast_1 = require("./acast");
Object.defineProperty(exports, "AcastIE", { enumerable: true, get: function () { return acast_1.AcastIE; } });
const art19_1 = require("./art19");
Object.defineProperty(exports, "Art19IE", { enumerable: true, get: function () { return art19_1.Art19IE; } });
const yandexmusic_1 = require("./yandexmusic");
Object.defineProperty(exports, "YandexMusicIE", { enumerable: true, get: function () { return yandexmusic_1.YandexMusicIE; } });
const audius_1 = require("./audius");
Object.defineProperty(exports, "AudiusIE", { enumerable: true, get: function () { return audius_1.AudiusIE; } });
const bandlab_1 = require("./bandlab");
Object.defineProperty(exports, "BandlabIE", { enumerable: true, get: function () { return bandlab_1.BandlabIE; } });
const reverbnation_1 = require("./reverbnation");
Object.defineProperty(exports, "ReverbNationIE", { enumerable: true, get: function () { return reverbnation_1.ReverbNationIE; } });
let registered = false;
function registerBuiltInExtractors() {
    if (registered)
        return;
    registered = true;
    (0, registry_1.registerExtractor)(video_1.YoutubeIE);
    // Batch 0 — embed / CDN platforms
    (0, registry_1.registerExtractor)(brightcove_1.BrightcoveIE);
    (0, registry_1.registerExtractor)(jwplatform_1.JWPlatformIE);
    (0, registry_1.registerExtractor)(wistia_1.WistiaIE);
    (0, registry_1.registerExtractor)(kaltura_1.KalturaIE);
    (0, registry_1.registerExtractor)(anvato_1.AnvatoIE);
    (0, registry_1.registerExtractor)(theplatform_1.ThePlatformIE);
    (0, registry_1.registerExtractor)(cloudflarestream_1.CloudflareStreamIE);
    (0, registry_1.registerExtractor)(bunnycdn_1.BunnyCdnIE);
    (0, registry_1.registerExtractor)(bitmovin_1.BitmovinIE);
    (0, registry_1.registerExtractor)(voxmedia_1.VoxMediaIE);
    // Batch 1 — global platforms
    (0, registry_1.registerExtractor)(vimeo_1.VimeoIE);
    (0, registry_1.registerExtractor)(twitch_1.TwitchIE);
    (0, registry_1.registerExtractor)(tiktok_1.TiktokIE);
    (0, registry_1.registerExtractor)(twitter_1.TwitterIE);
    (0, registry_1.registerExtractor)(instagram_1.InstagramIE);
    (0, registry_1.registerExtractor)(facebook_1.FacebookIE);
    (0, registry_1.registerExtractor)(reddit_1.RedditIE);
    (0, registry_1.registerExtractor)(soundcloud_1.SoundcloudIE);
    (0, registry_1.registerExtractor)(dailymotion_1.DailymotionIE);
    (0, registry_1.registerExtractor)(bilibili_1.BilibiliIE);
    // Batch 2 — VLC-oriented sites
    (0, registry_1.registerExtractor)(bandcamp_1.BandcampIE);
    (0, registry_1.registerExtractor)(rumble_1.RumbleIE);
    (0, registry_1.registerExtractor)(kick_1.KickIE);
    (0, registry_1.registerExtractor)(patreon_1.PatreonIE);
    (0, registry_1.registerExtractor)(bluesky_1.BlueskyIE);
    (0, registry_1.registerExtractor)(bitchute_1.BitchuteIE);
    (0, registry_1.registerExtractor)(newgrounds_1.NewgroundsIE);
    (0, registry_1.registerExtractor)(ninegag_1.NinegagIE);
    (0, registry_1.registerExtractor)(coub_1.CoubIE);
    (0, registry_1.registerExtractor)(peertube_1.PeertubeIE);
    // Batch 3 — regional APIs
    (0, registry_1.registerExtractor)(niconico_1.NiconicoIE);
    (0, registry_1.registerExtractor)(afreecatv_1.AfreecaTVIE);
    (0, registry_1.registerExtractor)(naver_1.NaverIE);
    (0, registry_1.registerExtractor)(iqiyi_1.IqiyiIE);
    (0, registry_1.registerExtractor)(youku_1.YoukuIE);
    (0, registry_1.registerExtractor)(fc2_1.FC2IE);
    (0, registry_1.registerExtractor)(weibo_1.WeiboIE);
    (0, registry_1.registerExtractor)(xiaohongshu_1.XiaoHongShuIE);
    (0, registry_1.registerExtractor)(vk_1.VKIE);
    (0, registry_1.registerExtractor)(odnoklassniki_1.OdnoklassnikiIE);
    // Batch 4 — audio / podcasts
    (0, registry_1.registerExtractor)(audiomack_1.AudiomackIE);
    (0, registry_1.registerExtractor)(applepodcasts_1.ApplePodcastsIE);
    (0, registry_1.registerExtractor)(mixcloud_1.MixcloudIE);
    (0, registry_1.registerExtractor)(soundgasm_1.SoundgasmIE);
    (0, registry_1.registerExtractor)(acast_1.AcastIE);
    (0, registry_1.registerExtractor)(art19_1.Art19IE);
    (0, registry_1.registerExtractor)(yandexmusic_1.YandexMusicIE);
    (0, registry_1.registerExtractor)(audius_1.AudiusIE);
    (0, registry_1.registerExtractor)(bandlab_1.BandlabIE);
    (0, registry_1.registerExtractor)(reverbnation_1.ReverbNationIE);
}
//# sourceMappingURL=register.js.map