"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getTokenStore = exports.TokenStore = exports.startWebServer = exports.createWebServer = exports.attachGvsPoToken = exports.ManualPoTokenProvider = exports.PoTokenDirector = exports.EJS_SCRIPT_VERSION = exports.VLC_CLIENTS = exports.DEFAULT_CLIENTS = exports.INNERTUBE_CLIENTS = exports.getURLVideoID = exports.getVideoID = exports.validateURL = exports.validateID = exports.YoutubeIE = exports.downloadFormat = exports.JA3_PROFILES = exports.browserHeadersFor = exports.createImpersonateTransport = exports.isImpersonateAvailable = exports.isCloudflareChallenge = exports.RequestClient = exports.createProxyAgent = exports.createAgent = exports.sortFormats = exports.selectFormats = exports.filterFormats = exports.chooseFormat = exports.migrationStatusBySite = exports.loadMigrationTracker = exports.withUrlUsage = exports.LIST_URL_USAGE = exports.URL_USAGE = exports.registerBuiltInExtractors = exports.InfoExtractor = exports.resolveListExtractor = exports.resolveExtractor = exports.findExtractorByName = exports.findExtractor = exports.listListCapableExtractors = exports.listExtractorInfo = exports.listExtractors = exports.registerExtractor = exports.listVideos = exports.extractInfo = exports.YoutubeDL = void 0;
var youtube_dl_1 = require("./core/youtube-dl");
Object.defineProperty(exports, "YoutubeDL", { enumerable: true, get: function () { return youtube_dl_1.YoutubeDL; } });
Object.defineProperty(exports, "extractInfo", { enumerable: true, get: function () { return youtube_dl_1.extractInfo; } });
Object.defineProperty(exports, "listVideos", { enumerable: true, get: function () { return youtube_dl_1.listVideos; } });
var registry_1 = require("./core/registry");
Object.defineProperty(exports, "registerExtractor", { enumerable: true, get: function () { return registry_1.registerExtractor; } });
Object.defineProperty(exports, "listExtractors", { enumerable: true, get: function () { return registry_1.listExtractors; } });
Object.defineProperty(exports, "listExtractorInfo", { enumerable: true, get: function () { return registry_1.listExtractorInfo; } });
Object.defineProperty(exports, "listListCapableExtractors", { enumerable: true, get: function () { return registry_1.listListCapableExtractors; } });
Object.defineProperty(exports, "findExtractor", { enumerable: true, get: function () { return registry_1.findExtractor; } });
Object.defineProperty(exports, "findExtractorByName", { enumerable: true, get: function () { return registry_1.findExtractorByName; } });
Object.defineProperty(exports, "resolveExtractor", { enumerable: true, get: function () { return registry_1.resolveExtractor; } });
Object.defineProperty(exports, "resolveListExtractor", { enumerable: true, get: function () { return registry_1.resolveListExtractor; } });
var info_extractor_1 = require("./core/info-extractor");
Object.defineProperty(exports, "InfoExtractor", { enumerable: true, get: function () { return info_extractor_1.InfoExtractor; } });
var register_1 = require("./extractor/register");
Object.defineProperty(exports, "registerBuiltInExtractors", { enumerable: true, get: function () { return register_1.registerBuiltInExtractors; } });
var url_usage_1 = require("./extractor/url-usage");
Object.defineProperty(exports, "URL_USAGE", { enumerable: true, get: function () { return url_usage_1.URL_USAGE; } });
Object.defineProperty(exports, "LIST_URL_USAGE", { enumerable: true, get: function () { return url_usage_1.LIST_URL_USAGE; } });
Object.defineProperty(exports, "withUrlUsage", { enumerable: true, get: function () { return url_usage_1.withUrlUsage; } });
var tracker_1 = require("./migration/tracker");
Object.defineProperty(exports, "loadMigrationTracker", { enumerable: true, get: function () { return tracker_1.loadMigrationTracker; } });
Object.defineProperty(exports, "migrationStatusBySite", { enumerable: true, get: function () { return tracker_1.migrationStatusBySite; } });
var format_select_1 = require("./core/format-select");
Object.defineProperty(exports, "chooseFormat", { enumerable: true, get: function () { return format_select_1.chooseFormat; } });
Object.defineProperty(exports, "filterFormats", { enumerable: true, get: function () { return format_select_1.filterFormats; } });
Object.defineProperty(exports, "selectFormats", { enumerable: true, get: function () { return format_select_1.selectFormats; } });
Object.defineProperty(exports, "sortFormats", { enumerable: true, get: function () { return format_select_1.sortFormats; } });
var request_1 = require("./networking/request");
Object.defineProperty(exports, "createAgent", { enumerable: true, get: function () { return request_1.createAgent; } });
Object.defineProperty(exports, "createProxyAgent", { enumerable: true, get: function () { return request_1.createProxyAgent; } });
Object.defineProperty(exports, "RequestClient", { enumerable: true, get: function () { return request_1.RequestClient; } });
var cloudflare_1 = require("./networking/cloudflare");
Object.defineProperty(exports, "isCloudflareChallenge", { enumerable: true, get: function () { return cloudflare_1.isCloudflareChallenge; } });
Object.defineProperty(exports, "isImpersonateAvailable", { enumerable: true, get: function () { return cloudflare_1.isImpersonateAvailable; } });
Object.defineProperty(exports, "createImpersonateTransport", { enumerable: true, get: function () { return cloudflare_1.createImpersonateTransport; } });
Object.defineProperty(exports, "browserHeadersFor", { enumerable: true, get: function () { return cloudflare_1.browserHeadersFor; } });
Object.defineProperty(exports, "JA3_PROFILES", { enumerable: true, get: function () { return cloudflare_1.JA3_PROFILES; } });
var http_1 = require("./downloader/http");
Object.defineProperty(exports, "downloadFormat", { enumerable: true, get: function () { return http_1.downloadFormat; } });
var video_1 = require("./extractor/youtube/video");
Object.defineProperty(exports, "YoutubeIE", { enumerable: true, get: function () { return video_1.YoutubeIE; } });
var base_1 = require("./extractor/youtube/base");
Object.defineProperty(exports, "validateID", { enumerable: true, get: function () { return base_1.validateID; } });
Object.defineProperty(exports, "validateURL", { enumerable: true, get: function () { return base_1.validateURL; } });
Object.defineProperty(exports, "getVideoID", { enumerable: true, get: function () { return base_1.getVideoID; } });
Object.defineProperty(exports, "getURLVideoID", { enumerable: true, get: function () { return base_1.getURLVideoID; } });
var clients_1 = require("./extractor/youtube/clients");
Object.defineProperty(exports, "INNERTUBE_CLIENTS", { enumerable: true, get: function () { return clients_1.INNERTUBE_CLIENTS; } });
Object.defineProperty(exports, "DEFAULT_CLIENTS", { enumerable: true, get: function () { return clients_1.DEFAULT_CLIENTS; } });
Object.defineProperty(exports, "VLC_CLIENTS", { enumerable: true, get: function () { return clients_1.VLC_CLIENTS; } });
var solver_1 = require("./extractor/youtube/jsc/solver");
Object.defineProperty(exports, "EJS_SCRIPT_VERSION", { enumerable: true, get: function () { return solver_1.EJS_SCRIPT_VERSION; } });
var pot_1 = require("./extractor/youtube/pot");
Object.defineProperty(exports, "PoTokenDirector", { enumerable: true, get: function () { return pot_1.PoTokenDirector; } });
Object.defineProperty(exports, "ManualPoTokenProvider", { enumerable: true, get: function () { return pot_1.ManualPoTokenProvider; } });
Object.defineProperty(exports, "attachGvsPoToken", { enumerable: true, get: function () { return pot_1.attachGvsPoToken; } });
var server_1 = require("./web/server");
Object.defineProperty(exports, "createWebServer", { enumerable: true, get: function () { return server_1.createWebServer; } });
Object.defineProperty(exports, "startWebServer", { enumerable: true, get: function () { return server_1.startWebServer; } });
var tokens_1 = require("./web/tokens");
Object.defineProperty(exports, "TokenStore", { enumerable: true, get: function () { return tokens_1.TokenStore; } });
Object.defineProperty(exports, "getTokenStore", { enumerable: true, get: function () { return tokens_1.getTokenStore; } });
const youtube_dl_2 = require("./core/youtube-dl");
exports.default = youtube_dl_2.YoutubeDL;
//# sourceMappingURL=index.js.map